# NumPy Basics

This notebook summarizes core NumPy concepts I learned as part of my Python for Data Science and Machine Learning coursework.

In [2]:
import numpy as np

## NumPy array creation
NumPy arrays are faster and more memory efficient than Python lists.

In [5]:
#First, we create a list and then convert it into a numpy array.
#one dimensional array
my_list=[1,2,3,4,5] 
my_list

[1, 2, 3, 4, 5]

In [6]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [7]:
#two dimensional array
matrix_list= [[1,2,3],[4,5,6],[7,8,9]]
matrix_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matrix_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# We can also save it to a variable

arr=np.array(matrix_list)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built in Methods 
NumPy has various built in methods 

## arange
### this returns an evenly spaced array and also helps in generating an array quickly


In [13]:
np.arange(5,15) #returns numbers from 5 upto 15 with an increment of 1 as default

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
#it does not include 15 because indexing in python starts from 0, so in this case it returns 10 digits.
np.arange(5,16) #if you want to include 15

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
np.arange(0,10,2) #we can also include a step size

array([0, 2, 4, 6, 8])

## zeros
### returns an array of zeros

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
#can also return a matrix/2-d array of zeros
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## linspace
### returns evenly spaced values over a specified interval

In [3]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

## rand
### returns an array of random values uniformly distributed between 0 and 1

In [4]:
np.random.rand(5)

array([0.66642504, 0.98412334, 0.77673315, 0.29240828, 0.98546655])

## randn
### returns an array of random values which are normally distributed 

In [5]:
np.random.randn(3,3)

array([[ 0.01905268, -0.88171897, -0.66320356],
       [ 1.43255654,  0.23010341,  0.7299879 ],
       [ 0.95087665, -0.24484268,  0.57874161]])

## randint
### returns integer values which lie in a specific range

In [6]:
np.random.randint(10,50,2)

array([42, 19])

## reshape
### returns a given array in a new shape

In [8]:
arr= np.arange(1,50,2) #create a numpy array
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [10]:
arr.reshape(5,5) #reshape changes the dimension of the array

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

## shape
### gives the dimensions of the array

In [13]:
arr.shape

(25,)

In [15]:
newarr= arr.reshape(5,5)
newarr.shape

(5, 5)

## dtype
### returns data type of the array

In [16]:
arr.dtype

dtype('int32')

# Indexing and Slicing
### this helps in selecting particular sections or values from an array

In [19]:
arr1= np.random.randint(0,50,10)
arr1

array([41, 41,  3,  3,  5,  7,  2, 14,  4, 24])

In [20]:
#returns value at a particular index
arr1[5]

7

In [23]:
#returns values from index 5 to terminal index
arr1[5:]

array([ 7,  2, 14,  4, 24])

In [24]:
#set a new value over a range
arr1[5:]=10
arr1

array([41, 41,  3,  3,  5, 10, 10, 10, 10, 10])

In [26]:
arr2=np.arange(0,11)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
slicedarray= arr2[5:]
slicedarray

array([ 5,  6,  7,  8,  9, 10])

In [30]:
slicedarray[:]=12 #set a new value
slicedarray

array([12, 12, 12, 12, 12, 12])

In [31]:
arr2 #it also changes the value in the original array so as to avoid memory issues.

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12, 12, 12])

In [33]:
#creating a 2d numpy array from a list
matarr=np.array(([1,2,3],[4,5,6],[7,8,9])) 
matarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
#slicing from a 2d array
matarr[2] #returns values from row index 2

array([7, 8, 9])

In [40]:
matarr[0:,2:] #returns values from column index 2

array([[3],
       [6],
       [9]])

In [41]:
matarr[1,1] #returns individual element

5

# Operations
### NumPy can perform a number of operations such as +, -, *, /, square root, min/max, exponent, logarithm, etc.

In [46]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr1= np.arange(11,21)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [47]:
arr+arr1 #returns sum of the two arrays

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [48]:
matarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
matarr.sum() #returns sum of all the elements in the array

45

In [50]:
arr*arr #returns multiplied elements in a list

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [54]:
cube= arr**3 # ** raises to the power
cube

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [55]:
cube.max() #returns max value from array

1000

In [63]:
square= np.square(arr1) #returns squared values
square

array([121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

In [64]:
np.sqrt(square) #returns square root values

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [69]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

## Boolean filtering
### selecting elements from an array based on true-false condition

In [80]:
list1=(78,98,34,65,59,40,85,46) #list of marks obtained
arr= np.array(list1)
arr

array([78, 98, 34, 65, 59, 40, 85, 46])

In [81]:
# returns true or false where marks is above 60
arr>60

array([ True,  True, False,  True, False, False,  True, False])

In [82]:
arr[arr>60] # returns an array with values above 60

array([78, 98, 65, 85])